In [7]:
import numpy as np

In [8]:
mylist = [i for i in range (10)]
type(mylist)

list

In [5]:
mylist*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
myarra = np.array(mylist)
type(myarra)

numpy.ndarray

In [10]:
myarra**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
mymatrix = np.array([[0,1,5],[-2,1,4],[7,8,9]])
mymatrix

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [13]:
mymatrix[:,0:1]

array([[ 0],
       [-2],
       [ 7]])

In [14]:
mymatrix[:,1:2]

array([[1],
       [1],
       [8]])

In [17]:
mymatrix[0:2,2:3]

array([[5],
       [4]])

In [19]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

In [24]:
Z = np.zeros(3)
Z

array([0., 0., 0.])

In [27]:
L = np.linspace(1,25,36)
L

array([ 1.        ,  1.68571429,  2.37142857,  3.05714286,  3.74285714,
        4.42857143,  5.11428571,  5.8       ,  6.48571429,  7.17142857,
        7.85714286,  8.54285714,  9.22857143,  9.91428571, 10.6       ,
       11.28571429, 11.97142857, 12.65714286, 13.34285714, 14.02857143,
       14.71428571, 15.4       , 16.08571429, 16.77142857, 17.45714286,
       18.14285714, 18.82857143, 19.51428571, 20.2       , 20.88571429,
       21.57142857, 22.25714286, 22.94285714, 23.62857143, 24.31428571,
       25.        ])

NameError: name 'df' is not defined